<?php

/**
 * @file
 * Contains facet_api_start_with_a_filter.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function facet_api_start_with_a_filter_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the facet_api_start_with_a_filter module.
    case 'help.page.facet_api_start_with_a_filter':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Filters out all the results that start with an &#039;A&#039;') . '</p>';
      return $output;

    default:
  }
}
